# Generated by Django 3.2.4 on 2021-06-28 23:19

import _io
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id',
            field=models.IntegerField(primary_key=_io.IncrementalNewlineDecoder, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='id',
            field=models.IntegerField(primary_key=_io.IncrementalNewlineDecoder, serialize=False),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id',
            field=models.IntegerField(primary_key=_io.IncrementalNewlineDecoder, serialize=False),
        ),
    ]
