# Generated by Django 3.2.4 on 2021-06-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_auto_20210628_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='listaProductos',
            field=models.CharField(max_length=64),
        ),
    ]
